const {test}=require('node:test');const assert=require('node:assert/strict');
const enabled=!!process.env.FIREBASE_AUTH_EMULATOR_HOST&&!!process.env.FIRESTORE_EMULATOR_HOST;
test('authenticated campus workflows preserve capacity, pricing, ownership and transitions',{skip:!enabled},async()=>{
 const {initializeApp}=require('firebase-admin/app');const {getAuth}=require('firebase-admin/auth');const {getFirestore,Timestamp}=require('firebase-admin/firestore');
 const app=initializeApp({projectId:'demo-civora'},'integration');const auth=getAuth(app),db=getFirestore(app);const suffix=Date.now().toString();
 async function actor(role,label=role){const uid=`${label}_${suffix}`;const email=`${uid}@test.civora.edu`;const password='EmulatorOnly123!';await auth.createUser({uid,email,password});if(role!=='student')await auth.setCustomUserClaims(uid,{role});await db.doc(`users/${uid}`).set({uid,email,name:role,role,department:'CSE',year:'2',section:'A',routeId:'',profileImage:'',notificationsEnabled:false,createdAt:Timestamp.now()});const response=await fetch(`http://${process.env.FIREBASE_AUTH_EMULATOR_HOST}/identitytoolkit.googleapis.com/v1/accounts:signInWithPassword?key=demo-key`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password,returnSecureToken:true})});return {uid,token:(await response.json()).idToken};}
 const student=await actor('student'),other=await actor('other'),vendor=await actor('vendor'),faculty=await actor('faculty'),admin=await actor('admin'),driver=await actor('driver');
 // 'other' is deliberately authenticated with an unrecognized role, and must fail privileged actions.
 async function call(user,name,data){try {const response=await fetch(`http://127.0.0.1:5001/demo-civora/us-central1/${name}`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${user.token}`},body:JSON.stringify({data}),signal:AbortSignal.timeout(90000)});return response.json();}catch(error){throw new Error(`${name} transport failure: ${error.cause?.code || error.message}`,{cause:error});}}
 async function success(user,name,data){const result=await call(user,name,data);assert.equal(result.error,undefined,JSON.stringify(result));return result.result;}
 async function denied(user,name,data){const result=await call(user,name,data);assert.ok(result.error,`Expected ${name} to fail`);}
 const wrongVendor=await actor('vendor','wrongVendor'),wrongDriver=await actor('driver','wrongDriver');
 await denied(student,'invitePrivilegedUser',{email:'forged@test.civora.edu',name:'Forged',role:'admin'});
 const invalid=await call(student,'eventRegistration',null);assert.equal(invalid.error?.status,'INVALID_ARGUMENT');
 const eventId=`event_${suffix}`,canteenId=`canteen_${suffix}`,menuItemId=`menu_${suffix}`,busId=`bus_${suffix}`,routeId=`route_${suffix}`;
 await db.doc(`events/${eventId}`).set({title:'Capacity test',description:'Test',category:'Workshop',venue:'Lab',organizer:'Faculty',createdBy:faculty.uid,department:'CSE',startTime:Timestamp.fromMillis(Date.now()+600000),endTime:Timestamp.fromMillis(Date.now()+3600000),capacity:1,registeredCount:0,registrationEnabled:true});
 const second=await actor('student2');await auth.setCustomUserClaims(second.uid,{role:'student'});
 // Refresh its token after issuing claims.
 const secondToken=await auth.createCustomToken(second.uid);const signed=await fetch(`http://${process.env.FIREBASE_AUTH_EMULATOR_HOST}/identitytoolkit.googleapis.com/v1/accounts:signInWithCustomToken?key=demo-key`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token:secondToken,returnSecureToken:true})});second.token=(await signed.json()).idToken;
 const race=await Promise.all([call(student,'eventRegistration',{eventId}),call(second,'eventRegistration',{eventId})]);assert.equal(race.filter(r=>!r.error).length,1);assert.equal((await db.doc(`events/${eventId}`).get()).data().registeredCount,1);
 const winner=race[0].error?second:student;const reg=await db.doc(`eventRegistrations/${eventId}_${winner.uid}`).get();assert.ok(reg.exists);await success(winner,'eventRegistration',{eventId});assert.equal((await db.doc(`events/${eventId}`).get()).data().registeredCount,1);
 await denied(other,'checkIn',{registrationId:reg.id,token:reg.data().token});await denied(faculty,'checkIn',{registrationId:reg.id,token:'fake'});await success(faculty,'checkIn',{registrationId:reg.id,token:reg.data().token});await denied(faculty,'checkIn',{registrationId:reg.id,token:reg.data().token});await denied(winner,'eventRegistration',{eventId,cancel:true});
 await denied(student,'publishCampusContent',{kind:'announcement',title:'Fake admin',body:'Fake',role:'admin'});
 await db.doc(`canteens/${canteenId}`).set({name:'Canteen',vendorId:vendor.uid,open:true});await db.doc(`menuItems/${menuItemId}`).set({name:'Meal',canteenId,pricePaise:5000,available:true});
 const requestId=`req_${suffix}`;const cart={canteenId,requestId,items:[{menuItemId,quantity:2,pricePaise:1}]};const order=await success(student,'placeFoodOrder',cart);assert.equal((await db.doc(`foodOrders/${order.orderId}`).get()).data().totalPaise,10000);assert.equal((await success(student,'placeFoodOrder',cart)).orderId,order.orderId);
 await denied(wrongVendor,'updateFoodOrder',{orderId:order.orderId,status:'ACCEPTED'});await denied(other,'updateFoodOrder',{orderId:order.orderId,status:'ACCEPTED'});await denied(vendor,'updateFoodOrder',{orderId:order.orderId,status:'READY'});
 for(const status of ['ACCEPTED','PREPARING','READY','COMPLETED'])await success(vendor,'updateFoodOrder',{orderId:order.orderId,status});await denied(vendor,'updateFoodOrder',{orderId:order.orderId,status:'PLACED'});
 const report=await success(student,'submitReport',{requestId,title:'Water leak',description:'Pipe leaking',category:'WATER',location:'Lab'});await denied(admin,'updateReport',{reportId:report.reportId,status:'RESOLVED'});await success(admin,'updateReport',{reportId:report.reportId,status:'ASSIGNED',assignedTo:'maintenance'});await success(admin,'updateReport',{reportId:report.reportId,status:'IN_PROGRESS'});await denied(admin,'updateReport',{reportId:report.reportId,status:'RESOLVED'});await success(admin,'updateReport',{reportId:report.reportId,status:'RESOLVED',resolutionNote:'Repaired'});
 await db.doc(`busRoutes/${routeId}`).set({name:'Route',stops:[]});await db.doc(`buses/${busId}`).set({name:'Bus',routeId,driverId:driver.uid});await denied(student,'manageTrip',{busId,active:true});await denied(wrongDriver,'manageTrip',{busId,active:true});await success(driver,'manageTrip',{busId,active:true});assert.equal((await db.doc(`activeTrips/${busId}`).get()).data().active,true);await denied(admin,'manageCampusData',{collection:'buses',id:busId,name:'Bus',routeId,driverId:wrongDriver.uid});await success(driver,'manageTrip',{busId,active:false});assert.equal((await db.doc(`activeTrips/${busId}`).get()).data().active,false);await success(admin,'manageCampusData',{collection:'buses',id:busId,name:'Bus',routeId,driverId:wrongDriver.uid});
 const activities=await db.collection('activities').where('userId','==',student.uid).get();assert.ok(activities.size>=6);
});
