package com.sachinkanna.civora.ui.student

import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import com.sachinkanna.civora.data.model.*
import com.sachinkanna.civora.viewmodel.*
import java.text.SimpleDateFormat
import java.util.*

private val dateFormat = SimpleDateFormat("EEE, dd MMM · h:mm a", Locale.getDefault())
@Composable fun AnnouncementFeed(vm: AnnouncementViewModel, onBack:()->Unit, onOpen:(Announcement)->Unit) { val s by vm.state.collectAsState(); LazyColumn(Modifier.fillMaxSize().padding(20.dp),verticalArrangement=Arrangement.spacedBy(14.dp)){ item{Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceBetween){TextButton(onClick=onBack){Text("Back")};Text("Announcements",style=MaterialTheme.typography.headlineSmall);IconButton(onClick=vm::refresh){Icon(Icons.Default.Refresh,"Refresh")}}}; item{Row(horizontalArrangement=Arrangement.spacedBy(8.dp)){FilterChip(s.category==null,{vm.setCategory(null)},label={Text("All")});FilterChip(s.category=="Academic",{vm.setCategory("Academic")},label={Text("Academic")});FilterChip(s.departmentOnly,{vm.setDepartmentOnly(!s.departmentOnly)},label={Text("My department")})}}; when {s.loading->item{CircularProgressIndicator()};s.error!=null->item{Text(s.error!!,color=MaterialTheme.colorScheme.error)};s.filtered.isEmpty()->item{Text("No announcements yet. Check back soon.",color=MaterialTheme.colorScheme.onSurfaceVariant)};else->items(s.filtered,key={it.id}){a->AnnouncementCard(a){onOpen(a)}}} } }
@Composable private fun AnnouncementCard(a:Announcement,onClick:()->Unit){Card(onClick=onClick,modifier=Modifier.fillMaxWidth(),colors=CardDefaults.cardColors(containerColor=if(a.priority.equals("high",true)||a.priority.equals("urgent",true)) MaterialTheme.colorScheme.errorContainer else MaterialTheme.colorScheme.surfaceVariant)){Column(Modifier.padding(18.dp),verticalArrangement=Arrangement.spacedBy(6.dp)){Text(a.category.uppercase(),style=MaterialTheme.typography.labelMedium,color=MaterialTheme.colorScheme.primary);Text(a.title,style=MaterialTheme.typography.titleLarge);Text(a.body,maxLines=2);if(a.department.isNotBlank())Text(a.department,style=MaterialTheme.typography.labelMedium)}}}
@Composable fun AnnouncementDetail(a:Announcement,onBack:()->Unit){LazyColumn(Modifier.fillMaxSize().padding(20.dp),verticalArrangement=Arrangement.spacedBy(14.dp)){item{TextButton(onClick=onBack){Text("Back")}};item{Text(a.title,style=MaterialTheme.typography.headlineMedium)};item{AssistChip(onClick={},label={Text("${a.category} · ${a.priority}")})};item{Text(a.body,style=MaterialTheme.typography.bodyLarge)};item{Text("Posted by ${a.authorName.ifBlank{"Civora campus"}}",color=MaterialTheme.colorScheme.onSurfaceVariant)}}}

@Composable fun EventsFeed(vm:EventsViewModel,uid:String,onBack:()->Unit,onOpen:(CampusEvent)->Unit){LaunchedEffect(uid){vm.load(uid)};val s by vm.state.collectAsState();LazyColumn(Modifier.fillMaxSize().padding(20.dp),verticalArrangement=Arrangement.spacedBy(14.dp)){item{Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceBetween){TextButton(onClick=onBack){Text("Back")};Text("Events",style=MaterialTheme.typography.headlineSmall)}};item{Row(horizontalArrangement=Arrangement.spacedBy(8.dp)){FilterChip(s.selectedCategory==null,{vm.setCategory(null)},label={Text("All")});FilterChip(s.selectedCategory=="Workshop",{vm.setCategory("Workshop")},label={Text("Workshops")});FilterChip(s.upcomingOnly,{vm.setUpcomingOnly(!s.upcomingOnly)},label={Text("Upcoming")})}};when{s.loading->item{CircularProgressIndicator()};s.error!=null->item{Text(s.error!!,color=MaterialTheme.colorScheme.error)};s.filtered.isEmpty()->item{Text("No events match these filters.",color=MaterialTheme.colorScheme.onSurfaceVariant)};else->items(s.filtered,key={it.id}){e->EventCard(e,e.id in s.registeredIds){onOpen(e)}}}}}
@Composable private fun EventCard(e:CampusEvent,registered:Boolean,onClick:()->Unit){Card(onClick=onClick,modifier=Modifier.fillMaxWidth()){Column(Modifier.padding(18.dp),verticalArrangement=Arrangement.spacedBy(7.dp)){Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceBetween){Text(e.category,style=MaterialTheme.typography.labelLarge,color=MaterialTheme.colorScheme.primary);if(registered)Icon(Icons.Default.CheckCircle,"Registered",tint=MaterialTheme.colorScheme.primary)};Text(e.title,style=MaterialTheme.typography.titleLarge);Text(if(e.startTime==0L)"Date to be announced" else dateFormat.format(Date(e.startTime)),style=MaterialTheme.typography.titleMedium);Text(e.venue.ifBlank{"Venue to be announced"},color=MaterialTheme.colorScheme.onSurfaceVariant)}}}
@Composable fun EventDetail(e:CampusEvent,vm:EventsViewModel,uid:String,onBack:()->Unit){val s by vm.state.collectAsState();val registered=e.id in s.registeredIds;Column(Modifier.fillMaxSize().padding(20.dp),verticalArrangement=Arrangement.spacedBy(16.dp)){TextButton(onClick=onBack){Text("Back")};Text(e.title,style=MaterialTheme.typography.headlineMedium);AssistChip(onClick={},label={Text(e.category)});Text(if(e.startTime==0L)"Date to be announced" else dateFormat.format(Date(e.startTime)),style=MaterialTheme.typography.titleMedium);Text("${e.venue.ifBlank{"Venue to be announced"}} · ${e.organizer.ifBlank{"Civora"}}");Text(e.description.ifBlank{"More details will be shared soon."},style=MaterialTheme.typography.bodyLarge);if(e.registrationEnabled)Button(onClick={vm.toggleRegistration(e.id,uid)},enabled=s.actionInProgress==null,modifier=Modifier.fillMaxWidth()){Text(if(registered)"Cancel RSVP" else "RSVP for this event")};s.error?.let{Text(it,color=MaterialTheme.colorScheme.error)}}}
